projects:

  # =========================
  # DEV - us-east-1
  # =========================

  - name: dev-us-east-1-ec2
    dir: environments/dev/us-east-1/ec2

  - name: dev-us-east-1-iam
    dir: environments/dev/us-east-1/iam

  - name: dev-us-east-1-s3
    dir: environments/dev/us-east-1/s3


  # =========================
  # DEV - ap-south-1
  # =========================

  - name: dev-ap-south-1-ec2
    dir: environments/dev/ap-south-1/ec2

  - name: dev-ap-south-1-iam
    dir: environments/dev/ap-south-1/iam

  - name: dev-ap-south-1-s3
    dir: environments/dev/ap-south-1/s3


  # =========================
  # DEV - eu-central-1
  # =========================

  - name: dev-eu-central-1-ec2
    dir: environments/dev/eu-central-1/ec2

  - name: dev-eu-central-1-iam
    dir: environments/dev/eu-central-1/iam

  - name: dev-eu-central-1-s3
    dir: environments/dev/eu-central-1/s3

auto_merge: false