formatter: markdown table

sections:
  hide: []
  show: []

sort:
  enabled: true
  by: required

settings:
  anchor: false
  escape: false
  lockfile: false
  required: false

output:
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
