apply_requirements:
  checks:
    - tag_query: ""
      approved:
        enabled: false

workflows:
  - tag_query: "'environments/dev/ap-south-1/s3/**' in dir"
    plan:
      - type: init
      - type: plan

engine:
  name: terraform
  version: 1.15.0 
