name: Digger - Dev

on:
<<<<<<< HEAD
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

  issue_comment:
    types:
      - created

=======
>>>>>>> 0ec0766366f174e1345ae28478f3b1026df1f5de
  workflow_dispatch:
    inputs:
      spec:
        description: "Digger project specification"
        required: true
        type: string

      run_name:
        description: "Digger run name"
        required: false
        type: string

run-name: "${{ inputs.run_name }}"

permissions:
  contents: write
  pull-requests: write
  issues: read
  statuses: write
  id-token: write

jobs:
  digger:
    name: Digger
    runs-on: ubuntu-latest
    environment: dev

    permissions:
      contents: write
      pull-requests: write
      issues: read
      statuses: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show Digger Job
        run: |
          echo "Digger job specification:"
          echo '${{ inputs.spec }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.15.0"
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: GitHubActions-Digger-Dev

      - name: Verify AWS Identity
        shell: bash
        run: aws sts get-caller-identity

      - name: Digger
        uses: diggerhq/digger@v0.6.147
        with:
<<<<<<< HEAD
          no-backend: true
=======
          digger-spec: ${{ inputs.spec }}
>>>>>>> 0ec0766366f174e1345ae28478f3b1026df1f5de
          setup-terraform: true
          terraform-version: "1.15.0"
          setup-aws: false
          cache-dependencies: true
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
