name: Terraform Deployment

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-dev:
    name: Terraform Plan and Apply - Dev
    runs-on: ubuntu-latest

    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Verify main branch
        if: github.ref != 'refs/heads/main'
        run: |
          echo "Deployment workflows must run from main."
          exit 1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.15.0"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::638631156706:role/GitHubActions-Terraform-Dev

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Terraform Init
        working-directory: environments/dev
        run: terraform init

      - name: Terraform Plan
        working-directory: environments/dev
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: environments/dev
        run: terraform apply -auto-approve tfplan
